### ISSUE TITLE
Entity 구현

### ISSUE THREAD

**Issue by sunseo18** [32th-SOPKATHON-TEAM8/SERVER#1]
## 📌 Feature Issue
- 엔티티 구현

## 📝 To-do

- [x] User 엔티티 구현
- [x] Group 엔티티 구현
- [x] Category 엔티티 구현
